# Generated by Django 4.1.5 on 2023-01-27 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn13', models.CharField(max_length=13)),
                ('isbn10', models.CharField(max_length=10)),
                ('title', models.CharField(max_length=100)),
                ('subtitle', models.CharField(max_length=100)),
                ('authors', models.CharField(max_length=100)),
                ('categories', models.CharField(max_length=100)),
                ('thumbnail', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=6000)),
                ('published_year', models.CharField(max_length=4)),
                ('average_rating', models.DecimalField(decimal_places=2, max_digits=5)),
                ('num_pages', models.IntegerField()),
                ('ratings_count', models.IntegerField()),
            ],
        ),
    ]
