# Generated by Django 4.1.5 on 2023-01-27 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='average_rating',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
